//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adv_details
    {
        public int user_id { get; set; }
        public string details { get; set; }
        public string img { get; set; }
        public int price { get; set; }
        public string area { get; set; }
        public string country { get; set; }
    }
}
